import {
  CORE_ICON_NAMES,
  EXPENSE_ICON_NAMES,
  GOAL_ICON_NAMES,
  INCOME_ICON_NAMES,
  STATUS_ICON_NAMES,
  type AppIconName,
} from "@/components/icons";

export const ICON_LABELS = {
  home: "Главная",
  transactions: "Операции",
  add: "Добавить",
  goals: "Хотелки",
  profile: "Профиль",
  eye: "Показать",
  "eye-off": "Скрыть",
  income: "Доход",
  expense: "Расход",
  transfer: "Перевод",
  card: "Карта",
  cash: "Наличные",
  savings: "Накопительный",
  "bank-account": "Банковский счёт",
  "custom-account": "Свой счёт",
  settings: "Настройки",
  logout: "Выйти",
  edit: "Изменить",
  archive: "Архив",
  calendar: "Календарь",
  target: "Цель",
  check: "Готово",
  warning: "Внимание",
  offline: "Нет сети",
  install: "Установить",
  share: "Поделиться",
  "home-screen": "На экран Домой",
  search: "Поиск",
  filter: "Фильтр",
  close: "Закрыть",
  back: "Назад",
  chevron: "Далее",
  categories: "Категории",
  "expense-groceries": "Продукты",
  "expense-transport": "Транспорт",
  "expense-cafe": "Кафе",
  "expense-housing": "Жильё",
  "expense-subscriptions": "Подписки",
  "expense-entertainment": "Развлечения",
  "expense-clothes": "Одежда",
  "expense-health": "Здоровье",
  "expense-education": "Образование",
  "expense-tech": "Техника",
  "expense-gifts": "Подарки",
  "expense-travel": "Путешествия",
  "expense-other": "Другое",
  "income-salary": "Зарплата",
  "income-side-job": "Подработка",
  "income-gift": "Подарок",
  "income-sale": "Продажа",
  "income-refund": "Возврат",
  "income-bonus": "Бонус",
  "income-other": "Другое",
  "goal-tech": "Техника",
  "goal-travel": "Путешествие",
  "goal-car": "Автомобиль",
  "goal-housing": "Жильё",
  "goal-education": "Образование",
  "goal-gift": "Подарок",
  "goal-clothes": "Одежда",
  "goal-health": "Здоровье",
  "goal-hobby": "Хобби",
  "goal-emergency-fund": "Финансовая подушка",
  "goal-other": "Другое",
  "status-active": "Активна",
  "status-completed": "Завершена",
  "status-archived": "В архиве",
  "status-cancelled": "Отменена",
  "priority-high": "Высокий",
  "priority-medium": "Средний",
  "priority-low": "Низкий",
} satisfies Record<AppIconName, string>;

export const ICON_GROUPS = [
  {
    title: "Интерфейс и счета",
    note: "Навигация, действия и типы счетов",
    names: CORE_ICON_NAMES,
  },
  {
    title: "Расходы",
    note: "Системные категории CategoryKind.EXPENSE",
    names: EXPENSE_ICON_NAMES,
  },
  {
    title: "Доходы",
    note: "Системные категории CategoryKind.INCOME",
    names: INCOME_ICON_NAMES,
  },
  {
    title: "Хотелки",
    note: "Все значения GoalCategory",
    names: GOAL_ICON_NAMES,
  },
  {
    title: "Состояния",
    note: "GoalStatus и GoalPriority",
    names: STATUS_ICON_NAMES,
  },
] as const;
